### ISSUE TITLE
SyntaxError in trivup.py:368

### ISSUE THREAD

**Issue by lerookie** [edenhill/trivup#5]
https://github.com/edenhill/trivup/blob/e8f5f548bfaed8d2d3be006303ba678199ec6583/trivup/trivup.py#L368

I believe this should be `except ValueError as e:` instead.

**Comment by rnpridgeon** [comment]
Looks like you were bit by a py2/py3 compatibility issue. 

https://www.python.org/dev/peps/pep-3110/

I'll submit a PR later today or tomorrow. In the meantime you can use virtualenv to specify the python 2 interpreter.
