### ISSUE TITLE
Exception: Deploy "/usr/lib/python2.6/site-packages/trivup/apps/KafkaBrokerApp/deploy.sh 0.8.1.1 "/tmp/librdkafka-1.0.0/tests/tmp/LibrdkafkaTestCluster/KafkaBrokerApp/kafka/0.8.1.1" "/tmp/librdkafka-1.0.0/tests/tmp/LibrdkafkaTestCluster/KafkaBrokerApp/kafka/0.8.1.1"" returned exit code 256

### ISSUE THREAD

**Issue by ckwillling** [edenhill/trivup#7]
I  run ./broker_version_tests.py  in librdkafka tests and got error 
```
Exception: Deploy "/usr/lib/python2.6/site-packages/trivup/apps/KafkaBrokerApp/deploy.sh 0.8.1.1 "/tmp/librdkafka-1.0.0/tests/tmp/LibrdkafkaTestCluster/KafkaBrokerApp/kafka/0.8.1.1" "/tmp/librdkafka-1.0.0/tests/tmp/LibrdkafkaTestCluster/KafkaBrokerApp/kafka/0.8.1.1"" returned exit code 256
```
Which point that

`/usr/lib/python2.6/site-packages/trivup/apps/KafkaBrokerApp/deploy.sh: Downloading 0.8.1.1 from http://apache.mirrors.spacedump.net/kafka/0.8.1.1/kafka_2.11-0.8.1.1.tgz`

The downloading url would always 404, when try:
```
curl http://apache.mirrors.spacedump.net/kafka/0.8.1.1/kafka_2.11-0.8.1.1.tgz
```  

So it does not work 

Please fix that

**Comment by my3** [comment]
Replace this line locally - https://github.com/edenhill/trivup/blob/bad11637e81a539b2168ca7eee1c5b4ee150ddc6/trivup/apps/KafkaBrokerApp/deploy.sh#L83

with another mirror URL from https://www.apache.org/dyn/closer.cgi?path=/kafka/2.2.0/kafka_2.11-2.2.0.tgz



You can try with utah.edu which may be a reliable and trusted host:

KAFKA_URL="http://apache.cs.utah.edu/kafka/${VERSION}/kafka_2.11-${VERSION}.tgz"


And then raise a Pull Request :)

**Comment by ckwillling** [comment]
0.8.1.1 only work with 
KAFKA_URL="http://apache.cs.utah.edu/kafka/${VERSION}/kafka_2.10-${VERSION}.tgz"

and close this issue
